language: elixir
install: true
sudo: false
elixir:
  - '1.8'
before_script:
  - "mix local.hex --force"
  - "mix local.rebar --force"
  - "mix deps.get"
  - "mix compile"

after_success:
  - MIX_ENV=test mix test
    #- MIX_ENV=test mix coveralls.travis

otp_release:
  - '21.0.9'
    #cache:
    #  directories:
    #    - _build
    #    - deps
services:
  - docker
